// src/app/search/muddaMapping.ts

export interface MuddaName {
    value: number;
    label: string;
  }

export interface MuddaType {
    value: number;
    label: string;
    names: MuddaName[];
  }

/**
 * Full mapping of muddha types to their respective names,
 * based on the provided mudda_names_and_types.txt data.
 */
export const muddaMapping: MuddaType[] = [
    {
      value: 1,
      label: 'दुनियाबादी देवानी',
      names: [
        { value: 385, label: '........' },
        { value: 1, label: 'अंश' },
        { value: 314, label: 'अंश जालसाजी' },
        { value: 186, label: 'अंशबन्डा' },
        { value: 423, label: 'अग्नि बिमा दाबी' },
        { value: 433, label: 'अधिकार पत्र बदर' },
        { value: 426, label: 'अनियमितता' },
        { value: 2, label: 'अपुताली' },
        { value: 300, label: 'अपुताली धनमाल' },
        { value: 419, label: 'अबन्डा जग्गा बन्डा' },
        { value: 326, label: 'अबन्डा धन बन्डा गराई पाउँ' },
        { value: 404, label: 'अर्को लिखत गराइपाऊँ' },
        { value: 245, label: 'अवैध रूपमा भवन निर्माण' },
        { value: 172, label: 'आदेश जारी गरी पाऊँ' },
        { value: 207, label: 'आदेश बदर' },
        { value: 262, label: 'आदेश बदर गरी हाजिर गराई पाउँ' },
        { value: 265, label: 'आम्दानी खर्च' },
        { value: 305, label: 'आयस्ता दिलाई पाऊँ' },
        { value: 307, label: 'आयस्ता वाली' },
        { value: 286, label: 'आर्य समाजी' },
        { value: 205, label: 'इन्साफ जाँच' },
        { value: 391, label: 'उखडा जग्गा' },
        { value: 258, label: 'उपयुक्त आदेश जारी गरी पाउँ' },
        { value: 241, label: 'क. ख. समेत' },
        { value: 192, label: 'कम्पनी सम्बन्धी' },
        { value: 3, label: 'करार' },
        { value: 388, label: 'कर्म थकाली' },
        { value: 291, label: 'कागज सच्यायो' },
        { value: 430, label: 'कित्ताकाट' },
        { value: 411, label: 'कित्ताकाट ट्रायल चेक' },
        { value: 359, label: 'किलास खिचोला' },
        { value: 347, label: 'किल्ला बदर' },
        { value: 253, label: 'कुत दिलाई मोही निष्काशन गरी पाउा' },
        { value: 343, label: 'कुत बाली' },
        { value: 180, label: 'कुलो पानी' },
        { value: 4, label: 'कुलो पानी' }, // Note: Duplicate label, different value
        { value: 5, label: 'क्षतिपुर्ति' },
        { value: 226, label: 'क्षेत्रफल सुधार' },
        { value: 155, label: 'खान लाउन दिलाई पाऊँ' },
        { value: 368, label: 'खानी लाइसेन्स बदर' },
        { value: 324, label: 'खिचोला' },
        { value: 185, label: 'खिचोला दर्ता बदर' },
        { value: 178, label: 'खिचोला पर्चा बदर गुठी' },
        { value: 215, label: 'खिचोला मेटाई' },
        { value: 195, label: 'खिचोला हक कायम' },
        { value: 6, label: 'गुठी सम्बन्धी' },
        { value: 243, label: 'गोश्वारा दर्ता कायम' },
        { value: 174, label: 'घर जग्गासम्बन्धी' },
        { value: 330, label: 'घर भत्काई पाऊँ' },
        { value: 315, label: 'घर भत्काई बाटो खुलाई' },
        { value: 7, label: 'घर भवन सम्बन्धी' },
        { value: 425, label: 'घरेलु हिंसा' },
        { value: 217, label: 'चलन चलाई पाऊँ' },
        { value: 212, label: 'चिकित्सकको रूपमा दर्ता गराइपाऊँ ।' },
        { value: 358, label: 'जग्गा खिचोला' },
        { value: 313, label: 'जग्गा जालसाजी' },
        { value: 427, label: 'जग्गा दर्ता नामसारी' },
        { value: 320, label: 'जग्गा निखनाई पाउँ' },
        { value: 282, label: 'जग्गा बाली' },
        { value: 8, label: 'जग्गा सम्बन्धी' },
        { value: 379, label: 'जातक मार्‍यो' },
        { value: 304, label: 'जायजात बेहिसाब' },
        { value: 325, label: 'जिउनी जग्गा' },
        { value: 269, label: 'जिमिदारी नामसारी' },
        { value: 403, label: 'जिरायत' },
        { value: 266, label: 'जोत कट्टा' },
        { value: 190, label: 'जोत कायम' },
        { value: 405, label: 'जोत बदर' },
        { value: 290, label: 'झुक्याई कागज गरायो' },
        { value: 382, label: 'टिकटको रूपैयाँ दिलाइ पाउँ' },
        { value: 139, label: 'ट्रेडमार्क दर्ता' },
        { value: 420, label: 'ट्रेडमार्क संशोधन' },
        { value: 229, label: 'ठेक्का रकम' },
        { value: 285, label: 'डाक रोकी पाउँ' },
        { value: 376, label: 'तलब दिलाई पाउँ' },
        { value: 322, label: 'तायदाती फैसला बदर' },
        { value: 200, label: 'तालुकी' },
        { value: 309, label: 'तिरो बुझाई पाऊँ' },
        { value: 339, label: 'थकाली लूय गरिपाऊँ' },
        { value: 401, label: 'थैली फिर्ता पाऊँ' },
        { value: 275, label: 'थैली बुझाई पाउँ' },
        { value: 247, label: 'दर्ता कायम' },
        { value: 336, label: 'दर्ता गरी पाउँ' },
        { value: 203, label: 'दर्ता बदर' },
        { value: 146, label: 'दर्ता बदर, नामसारी' },
        { value: 383, label: 'दाइजो पेवा' },
        { value: 183, label: 'दाखिल खारेज' },
        { value: 399, label: 'दामासाही गरिपाऊँ' },
        { value: 9, label: 'दुनियावादी देवानी विविध' },
        { value: 191, label: 'दूषित दर्ता' },
        { value: 280, label: 'दोहरा लिखत' },
        { value: 255, label: 'दोहोरो दर्ता श्रेस्ता' },
        { value: 10, label: 'धनमाल' },
        { value: 270, label: 'धरौट' },
        { value: 11, label: 'धर्मपुत्र / पुत्री' },
        { value: 169, label: 'धर्मपुत्र लिखत बदर' },
        { value: 136, label: 'धर्मलोप' },
        { value: 393, label: 'नक्सा पास' },
        { value: 346, label: 'नक्सा बेगर ढोका गोठ बनाएको भत्काई पाउँ' },
        { value: 259, label: 'नाता कायम' },
        { value: 161, label: 'नापी दर्ता बदर दर्ता' },
        { value: 171, label: 'नामसारी' },
        { value: 199, label: 'नासो धरौट' },
        { value: 202, label: 'निखनाई पाऊँ' },
        { value: 213, label: 'निर्णय दर्ता बदर' },
        { value: 141, label: 'निर्णय दर्ता बदर हक कायम दर्तासमेत' },
        { value: 162, label: 'निर्णय बदर समेत' },
        { value: 12, label: 'निर्वाचन' },
        { value: 210, label: 'निर्वाचन बदर' },
        { value: 188, label: 'निवेदन' },
        { value: 345, label: 'पदमा कायम' },
        { value: 362, label: 'पर्खाल खिचोला' },
        { value: 263, label: 'पर्खाल भत्काई सार्वजनिक कुलो कायम' },
        { value: 380, label: 'पर्चा बदर' },
        { value: 349, label: 'पर्वते रौजौटा कायम' },
        { value: 335, label: 'पसलबाट उठाई पाउँ' },
        { value: 297, label: 'पाल्ही भट्टि रकम' },
        { value: 397, label: 'पास गराई पाऊँ ।' },
        { value: 398, label: 'पास गराई पाऊँ ।' }, // Note: Duplicate label, different value
        { value: 13, label: 'पेटेन्ट ,डिजाइन,ट्रेडमार्क' },
        { value: 377, label: 'पैनी तोडी दियो' },
        { value: 308, label: 'पोत दिलाई पाऊँ' },
        { value: 396, label: 'फट्टा दिलाई पाउँ भन्ने' },
        { value: 350, label: 'फिल्डबुक सच्याएको दर्ता' },
        { value: 14, label: 'फैसला वदर' },
        { value: 316, label: 'बकस जग्गा' },
        { value: 149, label: 'बकसपत्र' },
        { value: 417, label: 'बच्चा जिम्मा लगाई पाउँ' },
        { value: 237, label: 'बन्डापत्र' },
        { value: 230, label: 'बन्धकी' },
        { value: 296, label: 'बन्धकी थैली' },
        { value: 206, label: 'बर्खास्ती बदर' },
        { value: 277, label: 'बहाल बुझाई पाउँ' },
        { value: 170, label: 'बहाल भराई पाउँ' },
        { value: 332, label: 'बाँध काट्यो' },
        { value: 264, label: 'बाटो खुलाई पाऊँ' },
        { value: 181, label: 'बालीसम्बन्धी' },
        { value: 182, label: 'बिक्री बदर' },
        { value: 361, label: 'बिक्रीकर निर्धारण' },
        { value: 175, label: 'बिगो असुल' },
        { value: 434, label: 'बिमा दाबी' },
        { value: 311, label: 'बेहिसावको नालिस खारेज' },
        { value: 246, label: 'बैक ग्यारेन्टी' },
        { value: 244, label: 'ब्याज भराई पाउँ' },
        { value: 248, label: 'भत्काई पाऊँ' },
        { value: 168, label: 'भरेङ बाटो कायम गरिपाऊँ ।' },
        { value: 167, label: 'भरेङ बाटो कायम गरिपाऊँ ।' }, // Note: Duplicate label, different value
        { value: 232, label: 'भाडा दिलाई घर खाली' },
        { value: 15, label: 'मध्यस्थता' },
        { value: 150, label: 'मानाचामल' },
        { value: 16, label: 'मिलापत्र' },
        { value: 351, label: 'मुद्दा सकार गरिपाऊँ' },
        { value: 17, label: 'मोही' },
        { value: 254, label: 'मोही निष्काशन' },
        { value: 221, label: 'म्याद तामेली' },
        { value: 145, label: 'रकम दिलाई भराई पाऊँ' },
        { value: 408, label: 'रसिद दिलाइ पाउँ' },
        { value: 261, label: 'राजिनामा दर्ता वदर हक कायम' },
        { value: 159, label: 'राजिनामा लिखत बदर' },
        { value: 354, label: 'राजिनामा सम्बन्धी' },
        { value: 353, label: 'राजीनामा खोसी झुक्याई सही गरायो' },
        { value: 374, label: 'रोक्का धनमाल हिनामिना' },
        { value: 239, label: 'रोक्का बदर' },
        { value: 272, label: 'रोक्का बाली फुकुवा पाउँ' },
        { value: 249, label: 'लगत सच्याई पाऊँ' },
        { value: 283, label: 'लिखत जालसाजी' },
        { value: 154, label: 'लिखत दर्ता बदर' },
        { value: 193, label: 'लिखत पारित' },
        { value: 337, label: 'लिखत पास' },
        { value: 317, label: 'लिखत फिर्ता पाउँ' },
        { value: 216, label: 'लिखत बदर' },
        { value: 166, label: 'लिज करारबोजिमको माल वस्तु नउठाउने र पुनः करारको आदेश' },
        { value: 18, label: 'लिलाम बदर' },
        { value: 19, label: 'लेनदेन' },
        { value: 20, label: 'वाटो निकास' },
        { value: 257, label: 'वाली मोही' },
        { value: 21, label: 'वाली विगो' },
        { value: 256, label: 'वाली सम्बन्धी' },
        { value: 250, label: 'विक्री सम्बन्धि' },
        { value: 22, label: 'वीमा' },
        { value: 23, label: 'वैना फिर्ता' },
        { value: 389, label: 'शेयर कायम गरिपाउँ' },
        { value: 390, label: 'शेयर सम्बन्धि' },
        { value: 144, label: 'शेषपछिको बकसपत्र' },
        { value: 194, label: 'सँधियार कायम गरी पाऊ' },
        { value: 252, label: 'संशोधन दाखिल खारेज' },
        { value: 220, label: 'सट्टापट्टा' },
        { value: 369, label: 'सन्धी सर्पन' },
        { value: 240, label: 'सफारी चलन' },
        { value: 400, label: 'समान जफत' },
        { value: 392, label: 'सम्पत्ति मसौट गरे भने' },
        { value: 364, label: 'सार्वजनिक जग्गा' },
        { value: 234, label: 'सार्वजनिक बाटो' },
        { value: 394, label: 'सावाँ ब्याज भराइपाउा' },
        { value: 281, label: 'सुन विदेश निकासी' },
        { value: 251, label: 'सेवाबाट अबकाश' },
        { value: 412, label: 'स्वीकृत किलोवाट कायम गरी हिसाब गराई पाउं' },
        { value: 140, label: 'हक कायम' },
        { value: 409, label: 'हक बेहक' },
        { value: 328, label: 'हकदार कायम' },
        { value: 179, label: 'हकसफा' },
        { value: 278, label: 'हद फुकाई पाउँ' },
        { value: 223, label: 'हदबन्दी' },
        { value: 295, label: 'हरण भएको जिमिदारी नम्बरी' },
        { value: 211, label: 'हरहिसाब गराइपाऊँ ।' },
        { value: 306, label: 'हर्जना दिलाई' },
        { value: 327, label: 'हाल आवादी' },
        { value: 293, label: 'हुण्डाबाली' },
        { value: 289, label: 'हेर्न नहुने मुद्दा हेर्‍यो' },
        { value: 363, label: '७ नं. फाँटवारी' },
      ],
    },
    {
      value: 2,
      label: 'सरकारबादी देवानी',
      names: [
        { value: 276, label: 'गैरकानूनी सस्पेन्ड' },
        { value: 402, label: 'तलब दिलाई पाऊँ' },
        { value: 415, label: 'रकम असुल' },
        { value: 24, label: 'सरकारी सम्पत्ति' },
      ],
    },
    {
      value: 3,
      label: 'दुनियावादी फौजदारी',
      names: [
        { value: 386, label: '.......' },
        { value: 25, label: 'अदल सम्बन्धी' },
        { value: 26, label: 'अदालतको अबहेलना' },
        { value: 27, label: 'ईलाज गर्ने' },
        { value: 424, label: 'उपभोक्ताको स्वास्थ्यमा प्रतिकूल असर' },
        { value: 28, label: 'करकाप' },
        { value: 29, label: 'करणी' },
        { value: 30, label: 'कीर्ते जालसाजी' },
        { value: 201, label: 'कुटपीट' },
        { value: 31, label: 'कुटपीट लुटपीट' },
        { value: 375, label: 'कोटाको कपडा' },
        { value: 32, label: 'गाली वेईज्जती' },
        { value: 371, label: 'गौचरन आवाद' },
        { value: 33, label: 'घरेलु हिंसा' },
        { value: 34, label: 'चेक अनादर' },
        { value: 35, label: 'चौपाया' },
        { value: 36, label: 'जारी' },
        { value: 152, label: 'जालसाज' },
        { value: 37, label: 'झुठ्ठा वकपत्र' },
        { value: 413, label: 'ठगी' },
        { value: 38, label: 'दुनियावादी फौजदारी विविध' },
        { value: 310, label: 'धनमाल करकाप' },
        { value: 39, label: 'नाताकायम' },
        { value: 356, label: 'बइजति' },
        { value: 323, label: 'बढी अन्न स्टक' },
        { value: 378, label: 'बिजाइ विद्युत' },
        { value: 40, label: 'बिहावारी' },
        { value: 357, label: 'बेइजति' },
        { value: 41, label: 'बौद्धिक सम्पत्ति सम्वन्धि' },
        { value: 42, label: 'यातना क्षतिपूर्ति' },
        { value: 176, label: 'लुटपिट' },
        { value: 319, label: 'लोग्ने कायम' },
        { value: 43, label: 'वाल श्रम' },
        { value: 44, label: 'विधुतीय कारोवार' },
        { value: 227, label: 'विवाह बदर' },
        { value: 45, label: 'सम्बन्ध विच्छेद' },
        { value: 370, label: 'साँध सिमाना' },
      ],
    },
    {
      value: 4,
      label: 'सरकारवादी फौजदारी',
      names: [
        { value: 46, label: 'अङ्गभङ' },
        { value: 47, label: 'अदल' },
        { value: 48, label: 'अध्यागमन सम्बन्धि' },
        { value: 342, label: 'अनियमितरूपमा मदिरा सञ्चालन' },
        { value: 340, label: 'अपशब्द' },
        { value: 49, label: 'अपहरण/ बन्धक' },
        { value: 130, label: 'अपहेलना' },
        { value: 50, label: 'अपाङ' },
        { value: 421, label: 'अप्राकृतिक मैथुन' },
        { value: 51, label: 'अभिलेख' },
        { value: 432, label: 'अमानवीय व्यवहार' },
        { value: 329, label: 'अवैध पैठारी' },
        { value: 406, label: 'अवैधानिक संघ संस्था खोले खोलाए' },
        { value: 52, label: 'आगलागी' },
        { value: 334, label: 'आदेश' },
        { value: 238, label: 'आदेश बदर' },
        { value: 53, label: 'आमाको दुध प्रतिस्थापन' },
        { value: 233, label: 'आयकर' },
        { value: 54, label: 'आवश्यक पदार्थ संबन्धी' },
        { value: 55, label: 'आवश्यक वस्तु संबन्धी' },
        { value: 56, label: 'आवश्यक सेवा संबन्धी' },
        { value: 57, label: 'उपभोक्ता हित सम्बन्धी' },
        { value: 58, label: 'औषधि' },
        { value: 59, label: 'कम्प्यूटर सम्बन्धी अपराध' },
        { value: 157, label: 'कर सम्बन्धी' },
        { value: 60, label: 'करणी' },
        { value: 131, label: 'कर्तव्य ज्यान' },
        { value: 135, label: 'कर्तव्यज्यान' },
        { value: 61, label: 'कालो बजारी' },
        { value: 160, label: 'किर्ते' },
        { value: 177, label: 'क्षतिपूर्ति' },
        { value: 299, label: 'खाद्यन्न स्टक' },
        { value: 62, label: 'खाध्य सम्बन्धी' },
        { value: 288, label: 'खुन' },
        { value: 63, label: 'खोटा चलन' },
        { value: 292, label: 'गर्भ तुहाउने उद्योग' },
        { value: 189, label: 'गर्भपतन' },
        { value: 64, label: 'गुणस्तर' },
        { value: 165, label: 'गैडासम्बन्धी' },
        { value: 344, label: 'गैर कानूनी' },
        { value: 65, label: 'गैर सैनिक हवाई उडान' },
        { value: 302, label: 'गैरकानूनी कारवाही' },
        { value: 321, label: 'गैह्रकानूनी लाभ' },
        { value: 331, label: 'गोली हान्यो' },
        { value: 66, label: 'गोवध' },
        { value: 67, label: 'चन्दा / चिठ्ठा' },
        { value: 68, label: 'चलचित्र' },
        { value: 395, label: 'चाँदी निकासी' },
        { value: 69, label: 'चोरी' },
        { value: 360, label: 'चोरी निकासी' },
        { value: 70, label: 'छात्रवृति' },
        { value: 71, label: 'छापाखाना' },
        { value: 72, label: 'जग्गा प्राप्ति' },
        { value: 73, label: 'जडिबुटी' },
        { value: 137, label: 'जबर्जस्ती करणी' },
        { value: 74, label: 'जलश्रोत' },
        { value: 158, label: 'जातीय छुवाछूत' },
        { value: 75, label: 'जासुसी सम्वन्धी' },
        { value: 151, label: 'जीउमास्ने बेच्ने' },
        { value: 76, label: 'जीवनाशक विषादि' },
        { value: 77, label: 'जुवा' },
        { value: 78, label: 'ज्यान' },
        { value: 184, label: 'ज्यान डाँका' },
        { value: 156, label: 'ज्यान मार्ने उद्योग' },
        { value: 79, label: 'ज्येष्ठ नागरिक' },
        { value: 333, label: 'झुक्याई सही छाप' },
        { value: 80, label: 'ठगी' },
        { value: 214, label: 'डाँका' },
        { value: 196, label: 'डाँका खुन' },
        { value: 164, label: 'डाँका चोरी' },
        { value: 367, label: 'तहबिल मसौट' },
        { value: 284, label: 'थुनछेक' },
        { value: 81, label: 'थुनुवा / कैदी भागे भगाएको' },
        { value: 82, label: 'दुरसंचार' },
        { value: 83, label: 'दैवी प्रकोप' },
        { value: 218, label: 'धर्म परिवर्तन' },
        { value: 301, label: 'धर्मलोप' },
        { value: 84, label: 'धितोपत्र कारोवार' },
        { value: 132, label: 'नकबजनी चोरी' },
        { value: 422, label: 'नक्कली नोट' },
        { value: 85, label: 'नागरिकता' },
        { value: 86, label: 'निर्वाचन अपराध' },
        { value: 222, label: 'नोकरीबाट हटाइएको' },
        { value: 87, label: 'नोटरी पव्लिक' },
        { value: 142, label: 'पर्ती जग्गा नामसारी गरी भ्रष्टाचार गरेको' },
        { value: 88, label: 'पशु स्वास्थय' },
        { value: 407, label: 'प्रकाशनको प्रमाणपत्र रद्द गरेको सम्बन्धमा' },
        { value: 89, label: 'प्रतिलिपि अधिकार सम्वन्धी' },
        { value: 90, label: 'प्रतिस्पर्धा सम्वन्धी' },
        { value: 268, label: 'प्राचिन मुर्ती चोरी' },
        { value: 153, label: 'बहुविवाह' },
        { value: 429, label: 'बाल यौन दुराचार' },
        { value: 91, label: 'बालबालिका बिरुद्धको अपराध' },
        { value: 384, label: 'बालहत्या' },
        { value: 92, label: 'बिबाह' },
        { value: 279, label: 'बेरीतसँग थुने' },
        { value: 93, label: 'बैंकिंङ अपराध' },
        { value: 431, label: 'बोक्सीको आरोप' },
        { value: 94, label: 'भ्रष्टाचार' },
        { value: 95, label: 'मानब अङ्ग बेचबिखन' },
        { value: 96, label: 'मानब वेचविखन तथा ओसार पसार' },
        { value: 224, label: 'मुद्दा फिर्ता' },
        { value: 267, label: 'मुर्ती चोरी' },
        { value: 418, label: 'मूल्य अभिवृद्धि कर' },
        { value: 341, label: 'मोटर चोरी' },
        { value: 294, label: 'मौलिक हक हनन' },
        { value: 414, label: 'रक्तचन्दन ओसारपसार' },
        { value: 235, label: 'राजकाज अपराध' },
        { value: 236, label: 'राजनीतिक उद्देश्यले संघ संस्था खोलेको' },
        { value: 97, label: 'राजश्व सम्वन्धी' },
        { value: 274, label: 'राज्य उलट पुलट' },
        { value: 98, label: 'राज्य बिरुद्धको अपराध' },
        { value: 99, label: 'राष्ट्र वैंक' },
        { value: 100, label: 'राहदानी संबन्धी' },
        { value: 287, label: 'रिभ्यु गरी पाउँ' },
        { value: 148, label: 'रिसवत' },
        { value: 101, label: 'लागुऔषध' },
        { value: 102, label: 'लिखतको गोप्यता' },
        { value: 103, label: 'वन' },
        { value: 104, label: 'वन्यजन्तु' },
        { value: 366, label: 'वाक तथा प्रकाशन स्वतन्त्रता' },
        { value: 105, label: 'विदेशी बिनिमय' },
        { value: 106, label: 'विदेशी विनिमय' },
        { value: 107, label: 'विधुतिय कारोबार' },
        { value: 231, label: 'विध्वंसात्मक अपराध' },
        { value: 365, label: 'विभागीय कारवाही' },
        { value: 108, label: 'विरुवा संरक्षण' },
        { value: 109, label: 'विवाह' },
        { value: 110, label: 'विविध' },
        { value: 111, label: 'विष्फोटक पदार्थ' },
        { value: 112, label: 'वैदेशिक रोजगार' },
        { value: 113, label: 'वैदेशिक रोजगार' }, // Note: Duplicate label, different value
        { value: 134, label: 'वैदेशिक रोजगार' }, // Note: Duplicate label, different value
        { value: 114, label: 'व्यक्तिगत धटना' },
        { value: 115, label: 'शिक्षा' },
        { value: 116, label: 'सम्पत्ति सुद्धिकरण' },
        { value: 117, label: 'सरकारी कागज छाप दस्तखत कीर्ते' },
        { value: 147, label: 'सरकारी छाप दस्तखत कीर्ते' },
        { value: 373, label: 'सरकारी सेवा प्रवेश' },
        { value: 372, label: 'सरकारी हानी नोक्सानी' },
        { value: 225, label: 'सवारी गौवध' },
        { value: 133, label: 'सवारी ज्यान' },
        { value: 318, label: 'सही रास्ता पत्रिका बन्द गरे' },
        { value: 118, label: 'सामाजिक अपराध' },
        { value: 119, label: 'सार्वजनिक अपराध' },
        { value: 120, label: 'सेना सम्बन्धी' },
        { value: 121, label: 'स्वास्थ्य व्यवसायी' },
        { value: 410, label: 'हकदार कायम गरिपाउँ' },
        { value: 271, label: 'हतियार चलाई काटेको' },
        { value: 242, label: 'हाडनाता करणी' },
        { value: 122, label: 'हातहतियार खरखजाना' },
        { value: 123, label: 'हुलाक' },
      ],
    },
    {
      value: 5,
      label: 'रिट',
      names: [
        { value: 348, label: '................' },
        { value: 124, label: 'अधिकारपृच्छा' },
        { value: 355, label: 'आज्ञा, आदेश वा पुर्जि जारी गरिपाऊँ' },
        { value: 125, label: 'उत्प्रेषण' },
        { value: 428, label: 'उत्प्रेषण / परमादेश' },
        { value: 303, label: 'खारेज ठाउँमा बसी काम गरे' },
        { value: 126, label: 'निषेधाज्ञा' },
        { value: 127, label: 'परमादेश' },
        { value: 128, label: 'प्रतिषेध' },
        { value: 129, label: 'बन्दीप्रत्यक्षीकरण' },
        { value: 143, label: 'विशेष रिट' },
        { value: 273, label: 'सरसियोररीको रिट जारी' },
      ],
    },
    {
      value: 6,
      label: 'निवेदन',
      names: [
        { value: 387, label: '...........' },
        { value: 173, label: 'आदेश संशोधन गरी पाऊँ' },
        { value: 187, label: 'टिप्पणी आदेश' },
        { value: 381, label: 'दरपीठ आदेश बदर गरी पाउँ' },
        { value: 197, label: 'निवेदन दर्ता गरी पाऊँ' },
        { value: 204, label: 'निवेदन/प्रतिवेदन' },
        { value: 138, label: 'पुनरावलोकन गरी पाऊँ ।' },
        { value: 260, label: 'पुनरावेदन सरह मुद्दा हेरी पाउँ' },
        { value: 338, label: 'पुनरावेदनको अनुमति पाऊँ' },
        { value: 208, label: 'बेरितको आदेश बदर' },
        { value: 209, label: 'मुद्दा दोहोर्‍याई हेरी पाऊँ' },
        { value: 352, label: 'मुद्दा सकार गरिपाऊँ' },
        { value: 298, label: 'मुद्दाको अनुमति' },
        { value: 198, label: 'मृत्यु दर्ता प्रमाणपत्र बदर ।' },
        { value: 219, label: 'संविधानसँग बाझिएका कानूनी प्रावधान अमान्य र बदर' },
      ],
    },
    {
      value: 7,
      label: 'विविध',
      names: [
        { value: 312, label: '...' },
        { value: 416, label: 'निर्देशन बदर' },
        { value: 228, label: 'माफी पाऊँ' },
      ],
    },
  ];